// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: spec.proto

package grpc

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KikoServiceClient is the client API for KikoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KikoServiceClient interface {
	// Add a new node to the system
	//
	// Create new node in the system
	AddNode(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*AddNodeResponse, error)
	// Create connection between nodes
	CreateConnection(ctx context.Context, in *CreateConnectionRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Delete connection between nodes
	DeleteConnection(ctx context.Context, in *DeleteConnectionRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Delete existing node
	DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Query recommended nodes for node
	//
	// Get k most recommended nodes for node n
	GetKRecommendations(ctx context.Context, in *GetKRecommendationsRequest, opts ...grpc.CallOption) (*GetKRecommendationsReponse, error)
	// Get existing node
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
}

type kikoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKikoServiceClient(cc grpc.ClientConnInterface) KikoServiceClient {
	return &kikoServiceClient{cc}
}

func (c *kikoServiceClient) AddNode(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*AddNodeResponse, error) {
	out := new(AddNodeResponse)
	err := c.cc.Invoke(ctx, "/kiko.KikoService/AddNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kikoServiceClient) CreateConnection(ctx context.Context, in *CreateConnectionRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/kiko.KikoService/CreateConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kikoServiceClient) DeleteConnection(ctx context.Context, in *DeleteConnectionRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/kiko.KikoService/DeleteConnection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kikoServiceClient) DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/kiko.KikoService/DeleteNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kikoServiceClient) GetKRecommendations(ctx context.Context, in *GetKRecommendationsRequest, opts ...grpc.CallOption) (*GetKRecommendationsReponse, error) {
	out := new(GetKRecommendationsReponse)
	err := c.cc.Invoke(ctx, "/kiko.KikoService/GetKRecommendations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kikoServiceClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, "/kiko.KikoService/GetNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KikoServiceServer is the server API for KikoService service.
// All implementations must embed UnimplementedKikoServiceServer
// for forward compatibility
type KikoServiceServer interface {
	// Add a new node to the system
	//
	// Create new node in the system
	AddNode(context.Context, *empty.Empty) (*AddNodeResponse, error)
	// Create connection between nodes
	CreateConnection(context.Context, *CreateConnectionRequest) (*empty.Empty, error)
	// Delete connection between nodes
	DeleteConnection(context.Context, *DeleteConnectionRequest) (*empty.Empty, error)
	// Delete existing node
	DeleteNode(context.Context, *DeleteNodeRequest) (*empty.Empty, error)
	// Query recommended nodes for node
	//
	// Get k most recommended nodes for node n
	GetKRecommendations(context.Context, *GetKRecommendationsRequest) (*GetKRecommendationsReponse, error)
	// Get existing node
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	mustEmbedUnimplementedKikoServiceServer()
}

// UnimplementedKikoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedKikoServiceServer struct {
}

func (UnimplementedKikoServiceServer) AddNode(context.Context, *empty.Empty) (*AddNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNode not implemented")
}
func (UnimplementedKikoServiceServer) CreateConnection(context.Context, *CreateConnectionRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConnection not implemented")
}
func (UnimplementedKikoServiceServer) DeleteConnection(context.Context, *DeleteConnectionRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteConnection not implemented")
}
func (UnimplementedKikoServiceServer) DeleteNode(context.Context, *DeleteNodeRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNode not implemented")
}
func (UnimplementedKikoServiceServer) GetKRecommendations(context.Context, *GetKRecommendationsRequest) (*GetKRecommendationsReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKRecommendations not implemented")
}
func (UnimplementedKikoServiceServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedKikoServiceServer) mustEmbedUnimplementedKikoServiceServer() {}

// UnsafeKikoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KikoServiceServer will
// result in compilation errors.
type UnsafeKikoServiceServer interface {
	mustEmbedUnimplementedKikoServiceServer()
}

func RegisterKikoServiceServer(s grpc.ServiceRegistrar, srv KikoServiceServer) {
	s.RegisterService(&KikoService_ServiceDesc, srv)
}

func _KikoService_AddNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KikoServiceServer).AddNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kiko.KikoService/AddNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KikoServiceServer).AddNode(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _KikoService_CreateConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KikoServiceServer).CreateConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kiko.KikoService/CreateConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KikoServiceServer).CreateConnection(ctx, req.(*CreateConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KikoService_DeleteConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KikoServiceServer).DeleteConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kiko.KikoService/DeleteConnection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KikoServiceServer).DeleteConnection(ctx, req.(*DeleteConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KikoService_DeleteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KikoServiceServer).DeleteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kiko.KikoService/DeleteNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KikoServiceServer).DeleteNode(ctx, req.(*DeleteNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KikoService_GetKRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KikoServiceServer).GetKRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kiko.KikoService/GetKRecommendations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KikoServiceServer).GetKRecommendations(ctx, req.(*GetKRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KikoService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KikoServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kiko.KikoService/GetNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KikoServiceServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KikoService_ServiceDesc is the grpc.ServiceDesc for KikoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KikoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kiko.KikoService",
	HandlerType: (*KikoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddNode",
			Handler:    _KikoService_AddNode_Handler,
		},
		{
			MethodName: "CreateConnection",
			Handler:    _KikoService_CreateConnection_Handler,
		},
		{
			MethodName: "DeleteConnection",
			Handler:    _KikoService_DeleteConnection_Handler,
		},
		{
			MethodName: "DeleteNode",
			Handler:    _KikoService_DeleteNode_Handler,
		},
		{
			MethodName: "GetKRecommendations",
			Handler:    _KikoService_GetKRecommendations_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _KikoService_GetNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spec.proto",
}
